# Generated by Django 2.2 on 2022-07-25 00:43

from django.db import migrations, models
import farm_base.models.owner


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0002_auto_20220723_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(default=farm_base.models.owner.get_sentinel_owner_id, on_delete=models.SET(farm_base.models.owner.get_sentinel_owner), to='farm_base.Owner', verbose_name='Owner'),
        ),
    ]
